// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8Q9lnfObPn1u1UYZkKiJPYxlRQHvGlhU',
    appId: '1:20378852161:web:f79d76d086a313d4fb1fc0',
    messagingSenderId: '20378852161',
    projectId: 'fir-1-fb4cf',
    authDomain: 'fir-1-fb4cf.firebaseapp.com',
    storageBucket: 'fir-1-fb4cf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeJlJskGDMmPuGE-TWqxFbp9V7ZOXgE5E',
    appId: '1:20378852161:android:3069d7733b0dde65fb1fc0',
    messagingSenderId: '20378852161',
    projectId: 'fir-1-fb4cf',
    storageBucket: 'fir-1-fb4cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBdVx8kByJwqpmFSCaAa6_sk-IJg4Nixc',
    appId: '1:20378852161:ios:62a82f02d8e86a53fb1fc0',
    messagingSenderId: '20378852161',
    projectId: 'fir-1-fb4cf',
    storageBucket: 'fir-1-fb4cf.appspot.com',
    iosClientId: '20378852161-mmfn0p8siki4ksnemcmfk8jstmgt81u8.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase1',
  );
}
